### ISSUE TITLE
Test example returns error in lm.fit

### ISSUE THREAD

**Issue by quantviews** [StuartGordonReid/emh#1]
> results <- is_random(S = global_indices$'YAHOO/INDEX_SML',
+                      a = 0.99, # To get a 99% confident result
+                      freqs1 = c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10),
+                      freqs2 = c("Mon", "Tue", "Wed", "Thu", "Fri", "Week", "Month"))
  |============================================================================================                                                                |  59%
Error in lm.fit(x, y, offset = offset, singular.ok = singular.ok, ...) : 
  0 (non-NA) cases

**Comment by StuartGordonReid** [comment]
Hi Quantviews, the notebook is running correctly on my side - just reran it now. Could you let me know what version of R and what operating system you are running on so I can try reproduce the issue?

**Comment by StuartGordonReid** [comment]
@quantviews are you still having this issue?
