### ISSUE TITLE
  LoadLibrary failure:  %1 is not a valid Win32 application.

### ISSUE THREAD

**Issue by stjordanis** [StuartGordonReid/emh#2]
In R studio, I cannot install the package, I get this:
*** arch - i386
Error in inDL(x, as.logical(local), as.logical(now), ...) : 
  unable to load shared object 'F:/R-3.3.2/library/emh/libs/i386/emh.dll':
  LoadLibrary failure:  %1 is not a valid Win32 application.
when running 
devtools::install_github(repo="stuartgordonreid/emh")
Please help, I have tried both 32/64 bit r versions, and much more....

**Comment by stjordanis** [comment]
full error message:
Installing emh
"F:/R-3.3.2/bin/x64/R" --no-site-file --no-environ --no-save  \
  --no-restore --quiet CMD INSTALL  \
  "C:/Users/Stel/AppData/Local/Temp/RtmpMv4Y7c/devtools223c13c71082/StuartGordonReid-emh-35dd7fd"  \
  --library="F:/R-3.3.2/library" --install-tests 

* installing *source* package 'emh' ...
** libs

*** arch - i386
make: Nothing to be done for `all'.
installing to F:/R-3.3.2/library/emh/libs/i386

*** arch - x64
make: Nothing to be done for `all'.
installing to F:/R-3.3.2/library/emh/libs/x64
** R
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
*** arch - i386
Error in inDL(x, as.logical(local), as.logical(now), ...) : 
  unable to load shared object 'F:/R-3.3.2/library/emh/libs/i386/emh.dll':
  LoadLibrary failure:  %1 is not a valid Win32 application.

Error: loading failed
Execution halted
*** arch - x64
ERROR: loading failed for 'i386'
* removing 'F:/R-3.3.2/library/emh'
Error: Command failed (1)

**Comment by stjordanis** [comment]
I used dependency walker to debug the emh.dll issue. 
 dll problems pop up in the dependency walker tool, they are system related:
API-MS-WIN-CORE-KERNEL32-PRIVATE-L1-1-1.DLL
API-MS-WIN-CORE-PRIVATEPROFILE-L1-1-1.DLL
API-MS-WIN-SERVICE-PRIVATE-L1-1-1.DLL
API-MS-WIN-CORE-SHUTDOWN-L1-1-1.DLL
EXT-MS-WIN-NTUSER-UICONTEXT-EXT-L1-1-0.DLL
IESHIMS.DLL
are missing       
I ran it on windows 8.1

Similarly, even more system dll files are reportedly missing when attempting to install your package on a win10 pc via rstudio

**Comment by stjordanis** [comment]
According to http://stackoverflow.com/questions/24778284/missing-dll-in-dependency-walker,
such messages on dependency walker are false positives, because the tool is outdated: http://www.dependencywalker.com/

**Comment by StuartGordonReid** [comment]
I've had this error before. I'm not sure what causes it, but a clean and rebuild on Windows usually does the trick and then I can reinstall. I am busy googling to see if there is a better explanation or solution to the problem. Sorry for the inconvenience, I'm still new to the package structure in R. It's pretty weird.

**Comment by StuartGordonReid** [comment]
@stjordanis, I've cleaned the package and fixed a bunch of small issues. I also uninstalled and reinstalled the package a bunch of times on my Windows 10 laptop successfully. Could you try again using devtools, and if that does not work, could you try the second approach I just added to the README?

**Comment by stjordanis** [comment]
Thank you, it gets installed on ubuntu 16  and the example runs like a charm, but fails in win8.1 and win10.
Could you please briefly describe the steps to clean and rebuild your work on Windows?

**Comment by stjordanis** [comment]
Thank you!!!
It works now on windows (i also tested it on ubuntu 16, works via devtools fine there). It failed when I tried to use devtools but when I git cloned it locally and made a clean build according to 
https://support.rstudio.com/hc/en-us/articles/200486508-Building-Testing-and-Distributing-Packages
it was installed and works fine!

**Comment by StuartGordonReid** [comment]
@stjordanis it's a pleasure I am just glad it works now. BTW I also added a road map for what I want to add to the package :-), just thought you might be interested in that.
