### ISSUE TITLE
Install on Windows with newest R

### ISSUE THREAD

**Issue by KonradMarcinPsiuk** [StuartGordonReid/emh#3]
Hi, when trying to install on Windows driven machine with R updated to the newest, I get this message:
dependency 'Rcpp' is not available for package 'emh'
Install through devtools

**Comment by StuartGordonReid** [comment]
Hey aby1ziomm, emh uses quite a bit of C++ code in the backend to speed things up. You can install Rcpp through Rstudio or R using install.packages('Rcpp') - http://adv-r.had.co.nz/Rcpp.html.

I hope that helps? Let me know if you run into any issues.

**Comment by KonradMarcinPsiuk** [comment]
hi , yeah I tried that but still the same issue, I updated R to the newest
as well

**Comment by KonradMarcinPsiuk** [comment]
HI, I managed to install package under fresh installation of R on Mac OS, however when I try to perform example code, when I run is_random function I get following error : 
Error in .Call("emh_cAsLogReturns", PACKAGE = "emh", levels, order) : 
  "emh_cAsLogReturns" not available for .Call() for package "emh"
